name: My test workflow
on:
 push:
  branches: [main]
Jobs:
  test build:
    runs on: ubuntu-latest
    steps:
     -name: getting the code 
      uses: actions/checkout@v4
      
      -name: Welcome
       run: echo "Hello from CI"
       
  
     
